DATA_CS = '../data/cityscapes/'
DATALIST_CS_TRAIN = './dataset/list/cityscapes/train.lst'
DATALIST_CS_VAL = './dataset/list/cityscapes/val.lst'
DATALIST_CS_TEST = './dataset/list/cityscapes/test.lst'

DATA_VOC = '../data/VOCdevkit/VOC2012/'
DATALIST_VOC_TRAIN = DATA_VOC + 'ImageSets/Segmentation/trainaug.txt'
DATALIST_VOC_VAL = DATA_VOC + 'ImageSets/Segmentation/val.txt'
DATALIST_VOC_TEST = 'None'

DATA_ADE20K = '../data/ADEChallengeData2016/'
DATA_ADE20K_TEST = '../data/ADEChallengeData2016/release_test/testing/'
DATALIST_ADE20K_TRAIN = './dataset/list/ade20k/train.txt'
DATALIST_ADE20K_VAL = './dataset/list/ade20k/val.txt'
DATALIST_ADE20K_TEST = '../data/ADEChallengeData2016/release_test/list.txt'

DATA_COCO = '../data/cocostuff/'
DATA_COCO_TEST = 'None'
DATALIST_COCO_TRAIN = './dataset/list/coco/train.txt'
DATALIST_COCO_VAL = './dataset/list/coco/val.txt'
DATALIST_COCO_TEST = 'None'
